### ISSUE TITLE
Warning does not matter, right?

### ISSUE THREAD

**Issue by BinhangYuan** [tensorflow/tensorboard-plugin-example#3]
Hi,
Am I the first user to fork this repository! I feel cool about that! ^.^

When I compile the code as the README.md suggested, although it succeeded, I got the following warnings:

> 2017-07-26 22:18:20.679 WARNING /tf-graph-info/tf-graph-icon.html.js:11: WARNING - Bad type annotation. Unknown type tf.graph.Node
>            * @type {tf.graph.Node}
>                     ^
> 
> 2017-07-26 22:18:20.820 WARNING /tf-graph-info/tf-graph-icon.html.js:22: WARNING - Bad type annotation. Unknown type tf.graph.render.RenderNodeInfo
>            * @type {tf.graph.render.RenderNodeInfo}
>                     ^
> 
> 2017-07-26 22:18:20.820 WARNING /tf-graph-info/tf-node-list-item.html.js:9: WARNING - Bad type annotation. Unknown type tf.graph.Node
>            * @type {tf.graph.Node}
>                     ^
> 
> 2017-07-26 22:18:20.821 WARNING /tf-graph-info/tf-node-list-item.html.js:14: WARNING - Bad type annotation. Unknown type tf.graph.Node
>            * @type {tf.graph.Node}
>                     ^
> 
> 2017-07-26 22:18:20.822 WARNING /tf-graph/tf-graph-scene.html.js:20: WARNING - Bad type annotation. Unknown type d3_zoom
>     /** @type {d3_zoom} d3 zoom object */
>                ^
> 
> 2017-07-26 22:18:20.822 WARNING /tf-graph/tf-graph-scene.html.js:60: WARNING - Bad type annotation. Unknown type d3.scale.ordinal
>      * @type {d3.scale.ordinal}
>               ^
> 
> 2017-07-26 22:18:20.822 WARNING /tf-graph/tf-graph-scene.html.js:67: WARNING - Bad type annotation. Unknown type tf.scene.Minimap
>      * @type {tf.scene.Minimap}
>               ^
> 
> 2017-07-26 22:18:20.823 WARNING 0 error(s), 7 warning(s), 63.2% typed
> INFO: From Vulcanizing /tensorboard.html:
> 2017-07-26 22:18:20.751 WARNING /tf-graph-info/tf-graph-icon.html.js:11: WARNING - Bad type annotation. Unknown type tf.graph.Node
>            * @type {tf.graph.Node}
>                     ^
> 
> 2017-07-26 22:18:20.820 WARNING /tf-graph-info/tf-graph-icon.html.js:22: WARNING - Bad type annotation. Unknown type tf.graph.render.RenderNodeInfo
>            * @type {tf.graph.render.RenderNodeInfo}
>                     ^
> 
> 2017-07-26 22:18:20.820 WARNING /tf-graph-info/tf-node-list-item.html.js:9: WARNING - Bad type annotation. Unknown type tf.graph.Node
>            * @type {tf.graph.Node}
>                     ^
> 
> 2017-07-26 22:18:20.821 WARNING /tf-graph-info/tf-node-list-item.html.js:14: WARNING - Bad type annotation. Unknown type tf.graph.Node
>            * @type {tf.graph.Node}
>                     ^
> 
> 2017-07-26 22:18:20.821 WARNING /tf-graph/tf-graph-scene.html.js:20: WARNING - Bad type annotation. Unknown type d3_zoom
>     /** @type {d3_zoom} d3 zoom object */
>                ^
> 
> 2017-07-26 22:18:20.822 WARNING /tf-graph/tf-graph-scene.html.js:60: WARNING - Bad type annotation. Unknown type d3.scale.ordinal
>      * @type {d3.scale.ordinal}
>               ^
> 
> 2017-07-26 22:18:20.822 WARNING /tf-graph/tf-graph-scene.html.js:67: WARNING - Bad type annotation. Unknown type tf.scene.Minimap
>      * @type {tf.scene.Minimap}
>               ^
> 
> 2017-07-26 22:18:20.823 WARNING 0 error(s), 7 warning(s), 63.1% typed

I guess it does not matter, right? It runs well in my browser.

**Comment by wchargin** [comment]
Correct: these seven warnings are known. See https://github.com/tensorflow/tensorboard/pull/149 for more details.

**Comment by BinhangYuan** [comment]
Thanks a lot! @wchargin

**Comment by wchargin** [comment]
You're welcome. :-)
